name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race --cover

    - name: Bench
      run: go test -benchmem -bench=. ./...
