on:
  push:
    branches: [master]
  pull_request:
    branches: [actions/readme]
jobs:
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Update readme according to Go doc
          uses: posener/goreadme@v1
          with:
            badge-godoc: 'true'
            functions: 'true'
