on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Update readme according to Go doc
          uses: posener/goreadme@v1
          with:
            badge-godoc: 'true'
            badge-goreadme: 'true'
            github-token: '${{ secrets.TOKEN }}'
            functions: 'true'
